# Generated by Django 3.0.7 on 2020-06-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50)),
                ('fname', models.CharField(blank=True, max_length=50)),
                ('lname', models.CharField(blank=True, max_length=50)),
                ('year_semester', models.CharField(choices=[('1st year 1st semester', '1st year 1st semester'), ('1st year 2nd semester', '1st year 2nd semester'), ('2nd year 1st semester', '2nd year 1st semester'), ('2nd year 2nd semester', '2nd year 2nd semester'), ('3rd year 1st semester', '3rd year 1st semester'), ('3rd year 2nd semester', '3rd year 2nd semester'), ('4th year 1st semester', '4th year 1st semester'), ('4th year 2nd semester', '4th year 2nd semester')], default='Select', max_length=50)),
                ('batch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('dept', models.CharField(blank=True, max_length=200)),
                ('teacherid', models.CharField(max_length=200, unique=True)),
                ('mobilenum', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
