# Generated by Django 3.0.7 on 2021-06-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_studentprofile_contantnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(default='img_avatar2.png', upload_to='profile_pic'),
        ),
    ]
